CREATE PROCEDURE [dbo].[GetCreditCardDetails]
	@NAME NVARCHAR(50) = NULL,
	@CARDNUMBER NVARCHAR(50) = NULL
AS

	IF(@NAME IS NULL AND @CARDNUMBER IS NULL)
	BEGIN
		SELECT * FROM [dbo].CreditCard 
	END
	ELSE IF(@NAME IS NOT NULL AND @CARDNUMBER IS NOT NULL)
		BEGIN
			SELECT * FROM [dbo].CreditCard WHERE Name LIKE @Name AND CardNumber LIKE @CARDNUMBER
		END