CREATE PROCEDURE [dbo].[InsertCreditCard]
	@NAME NVARCHAR(50),
	@CARDNUMBER NVARCHAR(50),
	@CVC  NVARCHAR(50),
	@EXPIRYDATE DATETIME
AS
	DECLARE @CARDID UNIQUEIDENTIFIER;
	SET @CARDID = NEWID();

	INSERT INTO [dbo].CreditCard (CardId, [Name], CardNumber, CVC, ExpiryDate) VALUES (@CARDID, @NAME, @CARDNUMBER, @CVC, @EXPIRYDATE)
	SELECT @CARDID
